/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Block: typeof import('./src/components/edit/block.vue')['default']
    Config: typeof import('./src/components/edit/config.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./src/components/edit/header.vue')['default']
    Render: typeof import('./src/components/edit/render.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VIcon: typeof import('./src/components/base/v-icon.vue')['default']
    VSelect: typeof import('./src/components/base/v-select.vue')['default']
  }
}
